Algoritmo "Aula7 Slide24 Exercício2"

// Crie um programa para ler 5 idades, calcular a média entre as idades e informar a média ao
// usuário.

Var

       idade, indice: inteiro
       media: real
     
Inicio

       para indice de 1 ate 5 faca
       
// entrada

         escreval("Digite a sua idade:")
         leia(idade)
         
 // processamento
 
         media <- media + idade
       fimpara

// saída

        escreval("A média das 5 idades é: ", media/5)
        
Fimalgoritmo